import 'package:flutter/material.dart';
import '../models/order.dart';
import 'order_confirmation_screen.dart';

class CheckoutScreen extends StatefulWidget {
  const CheckoutScreen({super.key});

  @override
  State<CheckoutScreen> createState() => _CheckoutScreenState();
}

class _CheckoutScreenState extends State<CheckoutScreen> {
  int _selectedPaymentMethod = 0;
  final List<PaymentMethod> _paymentMethods = [
    PaymentMethod(
      name: 'Credit / Debit Card',
      icon: 'assets/images/stripe.png',
      isSelected: true,
    ),
    PaymentMethod(
      name: 'PayPal',
      icon: 'assets/images/paypal.png',
      isSelected: false,
    ),
    PaymentMethod(
      name: 'Razorpay',
      icon: 'assets/images/razorpay.png',
      isSelected: false,
    ),
  ];

  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _addressController = TextEditingController();
  final _cityController = TextEditingController();
  final _postalCodeController = TextEditingController();
  final _countryController = TextEditingController();


// In the _confirmOrder method, update the order creation:
  void _confirmOrder() {
    if (_formKey.currentState!.validate()) {
      // Create order object
      final order = AppOrder(
        id: '', // Will be generated by Firestore
        userId: 'current_user_id', // Replace with actual user ID
        items: [], // Add cart items here
        totalAmount: 124.98,
        status: 'pending',
        createdAt: DateTime.now(),
        shippingAddress: ShippingAddress(
          fullName: _nameController.text,
          street: _addressController.text,
          city: _cityController.text,
          postalCode: _postalCodeController.text,
          country: _countryController.text,
        ),
        paymentInfo: PaymentInfo(
          method: _paymentMethods[_selectedPaymentMethod].name,
        ),
      );

      // Save order to database
      // DatabaseService().createOrder(order);

      Navigator.pushReplacement(
        context,
        MaterialPageRoute(
          builder: (context) => const OrderConfirmationScreen(),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF102222),
      appBar: AppBar(
        backgroundColor: const Color(0xFF102222),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          'Checkout',
          style: TextStyle(
            color: Colors.white,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        centerTitle: true,
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            // Shipping Address Section
            _buildSection(
              title: 'Shipping Address',
              child: Column(
                children: [
                  _buildTextField(
                    controller: _nameController,
                    label: 'Full Name',
                    hint: 'Jane Doe',
                  ),
                  const SizedBox(height: 16),
                  _buildTextField(
                    controller: _addressController,
                    label: 'Street Address',
                    hint: '123 Market St',
                  ),
                  const SizedBox(height: 16),
                  Row(
                    children: [
                      Expanded(
                        child: _buildTextField(
                          controller: _cityController,
                          label: 'City',
                          hint: 'San Francisco',
                        ),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: _buildTextField(
                          controller: _postalCodeController,
                          label: 'Postal Code',
                          hint: '94103',
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),
                  _buildTextField(
                    controller: _countryController,
                    label: 'Country',
                    hint: 'United States',
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),
            // Payment Method Section
            _buildSection(
              title: 'Payment Method',
              child: Column(
                children: _paymentMethods.asMap().entries.map((entry) {
                  final index = entry.key;
                  final method = entry.value;
                  return _buildPaymentMethodCard(method, index);
                }).toList(),
              ),
            ),
            const SizedBox(height: 24),
            // Order Summary Section
            _buildOrderSummary(),
            const SizedBox(height: 100), // Space for bottom button
          ],
        ),
      ),
      // Bottom Button
      bottomSheet: Container(
        color: const Color(0xFF102222),
        padding: const EdgeInsets.all(16),
        child: SizedBox(
          width: double.infinity,
          height: 56,
          child: ElevatedButton(
            onPressed: _confirmOrder,
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF0DF2F2),
              foregroundColor: const Color(0xFF102222),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(28),
              ),
            ),
            child: const Text(
              'Confirm & Pay \$124.98',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildSection({required String title, required Widget child}) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF162F2F),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(
              color: Colors.white,
              fontSize: 18,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 16),
          child,
        ],
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required String hint,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            color: Color(0xFF9CBABA),
            fontSize: 14,
            fontWeight: FontWeight.w500,
          ),
        ),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          style: const TextStyle(color: Colors.white),
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: const TextStyle(color: Color(0xFF9CBABA)),
            filled: true,
            fillColor: const Color(0xFF102222),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: Color(0xFF3B5454)),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: Color(0xFF3B5454)),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: Color(0xFF0DF2F2)),
            ),
          ),
          validator: (value) {
            if (value == null || value.isEmpty) {
              return 'This field is required';
            }
            return null;
          },
        ),
      ],
    );
  }

  Widget _buildPaymentMethodCard(PaymentMethod method, int index) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: _selectedPaymentMethod == index
            ? const Color(0xFF0DF2F2).withOpacity(0.2)
            : const Color(0xFF102222),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(
          color: _selectedPaymentMethod == index
              ? const Color(0xFF0DF2F2)
              : const Color(0xFF3B5454),
        ),
      ),
      child: RadioListTile<int>(
        value: index,
        groupValue: _selectedPaymentMethod,
        onChanged: (value) {
          setState(() {
            _selectedPaymentMethod = value!;
          });
        },
        title: Text(
          method.name,
          style: const TextStyle(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.w500,
          ),
        ),
        secondary: Image.asset(
          method.icon,
          height: 24,
        ),
        activeColor: const Color(0xFF0DF2F2),
        contentPadding: EdgeInsets.zero,
        controlAffinity: ListTileControlAffinity.trailing,
      ),
    );
  }

  Widget _buildOrderSummary() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF162F2F),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Order Summary',
            style: TextStyle(
              color: Colors.white,
              fontSize: 18,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 16),
          _buildSummaryRow('Subtotal', '\$119.98'),
          const SizedBox(height: 8),
          _buildSummaryRow('Shipping', '\$5.00'),
          const Divider(color: Colors.white24, height: 32),
          _buildSummaryRow('Total', '\$124.98', isTotal: true),
        ],
      ),
    );
  }

  Widget _buildSummaryRow(String label, String value, {bool isTotal = false}) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          label,
          style: TextStyle(
            color: const Color(0xFF9CBABA),
            fontSize: isTotal ? 18 : 16,
            fontWeight: isTotal ? FontWeight.bold : FontWeight.normal,
          ),
        ),
        Text(
          value,
          style: TextStyle(
            color: isTotal ? const Color(0xFF0DF2F2) : Colors.white,
            fontSize: isTotal ? 18 : 16,
            fontWeight: isTotal ? FontWeight.bold : FontWeight.normal,
          ),
        ),
      ],
    );
  }
}

class PaymentMethod {
  final String name;
  final String icon;
  final bool isSelected;

  PaymentMethod({
    required this.name,
    required this.icon,
    required this.isSelected,
  });
}